// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DevHabit.API.Migrations.Application
{
    /// <inheritdoc />
    public partial class AddTagHabits : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "tags",
                schema: "Application",
                columns: table => new
                {
                    id = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: false),
                    name = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    description = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    createdAtUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    updatedAtUtc = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pK_tags", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "habitTags",
                schema: "Application",
                columns: table => new
                {
                    habitId = table.Column<string>(type: "nvarchar(500)", nullable: false),
                    tagId = table.Column<string>(type: "nvarchar(500)", nullable: false),
                    createdAtUtc = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pK_habitTags", x => new { x.habitId, x.tagId });
                    table.ForeignKey(
                        name: "fK_habitTags_habits_habitId",
                        column: x => x.habitId,
                        principalSchema: "Application",
                        principalTable: "habits",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fK_habitTags_tags_tagId",
                        column: x => x.tagId,
                        principalSchema: "Application",
                        principalTable: "tags",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "iX_habitTags_tagId",
                schema: "Application",
                table: "habitTags",
                column: "tagId");

            migrationBuilder.CreateIndex(
                name: "IX_Tag_Name",
                schema: "Application",
                table: "tags",
                column: "name",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "habitTags",
                schema: "Application");

            migrationBuilder.DropTable(
                name: "tags",
                schema: "Application");
        }
    }
}
