// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DevHabit.API.Migrations.Application
{
    /// <inheritdoc />
    public partial class AddHabit : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(
                name: "Application");

            migrationBuilder.CreateTable(
                name: "habits",
                schema: "Application",
                columns: table => new
                {
                    id = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: false),
                    name = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    description = table.Column<string>(type: "nvarchar(500)", maxLength: 500, nullable: true),
                    type = table.Column<int>(type: "int", nullable: false),
                    frequency_Type = table.Column<int>(type: "int", nullable: false),
                    frequency_TimesPerPeriod = table.Column<int>(type: "int", nullable: false),
                    target_Value = table.Column<int>(type: "int", nullable: false),
                    target_Unit = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    status = table.Column<int>(type: "int", nullable: false),
                    isArchived = table.Column<bool>(type: "bit", nullable: false),
                    endDate = table.Column<DateOnly>(type: "date", nullable: true),
                    milestone_Target = table.Column<int>(type: "int", nullable: true),
                    milestone_Current = table.Column<int>(type: "int", nullable: true),
                    createdAtUtc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    updatedAtUtc = table.Column<DateTime>(type: "datetime2", nullable: true),
                    lastCompletedAtUtc = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pK_habits", x => x.id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "habits",
                schema: "Application");
        }
    }
}
