// <auto-generated />
using System;
using DevHabit.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevHabit.API.Migrations.Application
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250528151130_AddTagHabits")]
    partial class AddTagHabits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Application")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevHabit.API.Domain.Entites.Habit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAtUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("endDate");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit")
                        .HasColumnName("isArchived");

                    b.Property<DateTime?>("LastCompletedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastCompletedAtUtc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAtUtc");

                    b.HasKey("Id")
                        .HasName("pK_habits");

                    b.ToTable("habits", "Application");
                });

            modelBuilder.Entity("DevHabit.API.Domain.Entites.HabitTag", b =>
                {
                    b.Property<string>("HabitId")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("habitId");

                    b.Property<string>("TagId")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("tagId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAtUtc");

                    b.HasKey("HabitId", "TagId")
                        .HasName("pK_habitTags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("iX_habitTags_tagId");

                    b.ToTable("habitTags", "Application");
                });

            modelBuilder.Entity("DevHabit.API.Domain.Entites.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAtUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAtUtc");

                    b.HasKey("Id")
                        .HasName("pK_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Tag_Name");

                    b.ToTable("tags", "Application");
                });

            modelBuilder.Entity("DevHabit.API.Domain.Entites.Habit", b =>
                {
                    b.OwnsOne("DevHabit.API.Domain.Entites.Frequency", "Frequency", b1 =>
                        {
                            b1.Property<string>("HabitId")
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("id");

                            b1.Property<int>("TimesPerPeriod")
                                .HasColumnType("int")
                                .HasColumnName("frequency_TimesPerPeriod");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("frequency_Type");

                            b1.HasKey("HabitId");

                            b1.ToTable("habits", "Application");

                            b1.WithOwner()
                                .HasForeignKey("HabitId")
                                .HasConstraintName("fK_habits_habits_id");
                        });

                    b.OwnsOne("DevHabit.API.Domain.Entites.Milestone", "Milestone", b1 =>
                        {
                            b1.Property<string>("HabitId")
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("id");

                            b1.Property<int>("Current")
                                .HasColumnType("int")
                                .HasColumnName("milestone_Current");

                            b1.Property<int>("Target")
                                .HasColumnType("int")
                                .HasColumnName("milestone_Target");

                            b1.HasKey("HabitId");

                            b1.ToTable("habits", "Application");

                            b1.WithOwner()
                                .HasForeignKey("HabitId")
                                .HasConstraintName("fK_habits_habits_id");
                        });

                    b.OwnsOne("DevHabit.API.Domain.Entites.Target", "Target", b1 =>
                        {
                            b1.Property<string>("HabitId")
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("target_Unit");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("target_Value");

                            b1.HasKey("HabitId");

                            b1.ToTable("habits", "Application");

                            b1.WithOwner()
                                .HasForeignKey("HabitId")
                                .HasConstraintName("fK_habits_habits_id");
                        });

                    b.Navigation("Frequency")
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("DevHabit.API.Domain.Entites.HabitTag", b =>
                {
                    b.HasOne("DevHabit.API.Domain.Entites.Habit", null)
                        .WithMany("HabitTags")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_habitTags_habits_habitId");

                    b.HasOne("DevHabit.API.Domain.Entites.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_habitTags_tags_tagId");
                });

            modelBuilder.Entity("DevHabit.API.Domain.Entites.Habit", b =>
                {
                    b.Navigation("HabitTags");
                });
#pragma warning restore 612, 618
        }
    }
}
